version: '3.8'
services:
  service:
    container_name: service
    image: citrus-playground/service
    build:
      context: ../service
      dockerfile: ../service/src/main/docker/Dockerfile
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      QUARKUS_LAUNCH_DEVMODE: true
      QUARKUS_REST_CLIENT__EXTERNAL__URL: http://citrus-tests:8080
    ports:
      - '8080:8080'
      - '5006:5005'
  citrus-tests:
    container_name: citrus-tests
    image: citrus-playground/citrus-tests
    build:
      context: ../citrus
      dockerfile: ../citrus/src/test/docker/Dockerfile
    command:
      - '--skipTests'
      - 'true'
      - '--duration'
      - '9223372036854775807'
    environment:
      HTTP_SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SUT_URL: http://service:8080
    ports:
      - '4567:4567'
      - '5007:5005'